voteamerica/voteamerica.github.io

index.html
res/styles.css

Removing CSS from markup and formatting HTML

cleanup of markup

---

index.html
res/styles.css

Fixing up mobile styles to be more like desktop styles and starting work on desktop styles

updating styles to be more sensible

---

index.html

Update wheelchair wording

---

index.html

Based on previous for options, added  subtitle/heading(left) with checkbox and description text(right) for both Driver form and Rider form.

Stay in touch checkbox for Rider and Driver forms (default=Checked)

---

index.html

Changed Text on Rider and Driver Forms at top.  Wasn't sure about hyperlink that is mentioned in the issue.

WIP: unsure about hyperlink

---

index.html

Update Tweet Text

---

index.html

This code mainly checks all the required fields needed for submission and allows the submit button to be enabled if the fields are filled out. The code only checks if there is a string of length greater than 0 for each required field. A lot of the special pop-up stuff that asks to fill in the required field if nothing in in the field is done by bootstrap.

Added some data validation code.

---

dropdown.js
index.html
res/styles.css

* Links open in new window.
* Added description paragraph to Are You Registered
* Changed style of Are You Registered
* Moved are you registered to above rock-the-vote stuff

updating PR with items from #58

---

index.html
res/styles.css

Am I registered  on top as heading.

switch am i registered to top

---

dropdown.js
index.html
res/location-details.json
res/styles.css

* Added separate Json file for each dropdown; the one in rock the vote and this one in rider form box 
* will refactor in a separate branch for both dropdowns once this is merged

added seperate JSON to solve conflicts from Polling-Location-Finder

---

index.html

- Changes "wheelchair" to input text field.

Updates #44

---

index.html

Fixes #44 in master.

---

index.html
res/styles.css

Add some general styling updates to get the site looking a bit more like the design:
I haven't styled the form much yet or gotten the buttons working again. Ultimately I'd like to move the two forms into their own pages and turn the two buttons into links, which would allow users to use the back button to easily get back to the main page, and make logic a bit easier. However I'm avoiding starting that until I'm sure others agree with this plan.

Design updates (header/nav/intro/form/button)

---

index.html
res/styles.css

This PR fixes issue #73 and also improves the styling on this section:

#73 Delete duplicate Voting Support copy

---

index.html
res/styles.css

- Remove the newsletter signup box (Issue #95)
- Add Election Countdown clock (Issue #94)
- Add YouTube button (Issue #93)

Remove newsletter, add countdown, add YouTube button

---

index.html

A bunch of signup form changes for @sasjkia, as requested in issues #96 & #97.
There's a few new/changed/deleted form name attributes here. We're going to have to update these on the backend too:
- `VehicleRegistrationNumber` -> `DriverLicenceNumber`
- new `DriverWillTakeCare` checkbox
- new `RiderWillBeSafe` checkbox (why did I name these inconsistently? oops)
- remove `RiderVotingState`
- new `riderNotes`

Various signup form updates

---

index.html

Applies date formatting used for driver dates to rider dates
Workaround for datepicker not specifying year

Date formatting

---

index.html

resolves https://github.com/voteamerica/backend/issues/35

change field name to match db field

---

index.html
res/styles.css

- Fix form columns on mobile
- Make the datepicker colour theme more consistent with the rest of the site
- Change slider bg-colour to gray so that it doesn’t distract from the button
- Move add-time buttons to top of right-column

Fix/improve form CSS

---

index.html
res/styles.css

- Fix zip code validation (fixing issue #101)
- Make the legal checkboxes required
- Move Moment.js script tag to the end of the page, and also remove commented-out bootstrap link, and remove duplicate bootstrap validator script tag.
- Major form submission JS refactor/simplification 😃
- Make the legal checkboxes required (cc @sasjkia)
I've managed to simplify the form JS a lot by generalising the behaviour, and by saving the date/time data to the button using `jQuery.data()`, then joining it on submit. I hope this works! ✌️

Form JS updates

---

index.html
res/styles.css

Make a start on improving the date/time UI usability, as discussed in #124.
- Change datetime to single column
- Add datetime form validation, to prevent users submitting a form with no times added

Improve form datetimepicker UX

---

index.html
story/index.html

For https://github.com/voteamerica/voteamerica.github.io/issues/86
I didn't add the nav links from the home page. I noticed that when redirected, some part gets dislocated or missing like this one: http://carpoolvote.com/#support.

Shorten Our Story text and move bulk of content to separate page

---

index.html

- Change "voting relating" to "voting related" for Issue #140 
- Add space after period for new sentence on home page "...and women. Carpool..."

Fix typo on home page✏️

---

index.html
res/styles.css
story/index.html

- Improve heading hierarchy
- Add alt/width/height attributes on images
- Minor copy improvements
- Remove deprecated link to dropdown.js (fixes #143)
- Improve footer styling/accessibility
- Improve form styling on mobile
- Prevent countdown iframe breaking layout on mobile
- Add Driver preferred contact method inputs and make JS toggle more universal (fixes #145)

Various a11y, styling and copy changes

---

selfservice.html
selfservice.js

@richardwestenra @dmilet working prototype of self-service page. Page is accessed via links in email or sms message. Params provided via querystring. The input field enables driver or rider to enter a confirmation value
Supported (and tested) for : 
User story 3
Supports cancel rider request 
(relevant sms/email link shown in User story 1)
User story 13
Supports cancel drive offer 
(relevant sms/email link shown in User story 11)
User story 15
driver accepts match
(relevant sms/email link shown in User story 15)

working prototype

---

selfservice.html
selfservice.js

@richardwestenra @dmilet update of working prototype of self-service page. 
Supported (and tested) for : 
User story 4 and 14 (google doc updated and describes how system works with this page)

support for cancelling confirmed match by driver and rider

---

index.html

Minor text change - Removed duplicate "how" in vehicle requirements

corrects duplication in vehicle requirements text

---

index.html
story/index.html

- Tweet button text changed to : "Support #Democracy4All this #Election2016. Sign up on @CarpoolVote: Linking drivers with voters needing a ride" (fixes #154)
- Change Facebook sharing button text (fixes #155)

Update Facebook and Twitter social sharing text

---

scripts/selfservice.js
self-service/index.html

support for new pause driver match db function, info field added beneath form to guide user. 
Buttons are only shown if supported by uuids provided. User is warned if confirmation text not entered. If server response is received this is shown in info field.

Self service page enhancements

---

index.html
scripts/main.js
styles/main.css

Add 'Optional' labels next to form input fields which aren't required

---

index.html
story/index.html
terms-conditions.html

Create a new html page "terms-conditions.html": Fixes #161

Created new page terms-conditions.html

---

index.html
styles/main.css

#96 - Added in Rider pick up and destination addresses.

Rider collection address

---

docs/contributing.md

Something from the Hacktoberfest search

Added mailto: to email

---

thanks-driver/index.html

I've changed tweet text on DRIVER confirmation page which was showing tweet text for RIDER page.
(Pls refer to Issue #202)

Changed tweet text on DRIVER confirmation page

---

index.html
scripts/map.js

Added dependencies to index.html & reconfigured marker code to use
clustering. This gives the map a cleaner, more usable look.

Implemented leaflet.markercluster plug-in.

---

index.html

banner changes for voteamerica/voteamerica.github.io#203

---

index.html
thanks-driver/index.html
thanks-rider/index.html

- Make T&C checkboxes required and make the names/IDs unique
- Fix self-service redirect QS bug (fixes #198 and resolves #209).

Fix thanks redirect URL query string bug

---

scripts/selfservice.js
self-service/index.html

@richardwestenra this PR makes use of the APIs provided by https://github.com/voteamerica/backend/pull/88 for the self service page. The code and html here give examples of using the API. All necessary data is provided. 
Be aware that certain APIs return multiple results. This is fairly clear from the forEach code.

Self service proto

---

index.html

update notes text box
- This time worked on updated version of master.
Please reject the **other** pull request by me.

update notes text box

---

how-it-works/index.html
index.html
self-service/index.html
story/index.html
styles/main.css
terms-conditions/index.html
thanks-driver/index.html
thanks-rider/index.html

Fixes #216 
Desktop view:
Mobile view:

Add Google Translate button to all pages

---

index.html

Make the minimum number of seats required == 1

---

faq/index.html
index.html

Add FAQ page

---

scripts/selfservice.js
self-service/index.html

supports cancel for rider and driver on confirmed matches
no longer displays buttons that cannot operate
refreshes on accept, cancel or multiple logins
general tidying

Self service cancel

---

index.html
styles/main.css

Changed styling to ensure input field does not overflow.

Fix input field in checkbox

---

index.html
styles/main.css

- Add GitHub link to support section: 
> "If you're a web developer, then consider contributing to our website on <a href="https://github.com/voteamerica/" target="_blank">GitHub</a>"
-  Fix [validation errors](https://validator.w3.org/nu/?doc=http%3A%2F%2Fcarpoolvote.com%2F).
- Add a link hover state.

Fix a11y and HTML validation errors

---

faq/index.html
how-it-works/index.html
self-service/index.html
story/index.html
terms-conditions/index.html
thanks-driver/index.html
thanks-rider/index.html

remove ourvote from banners
fixes https://github.com/voteamerica/voteamerica.github.io/issues/240

corrected banner phone numbers

---

scripts/selfservice.js
self-service/index.html
styles/main.css

Added styles to remove extra bullet points. Added margin under each button at bottom of lists.

Improving accept button on self service page

---

scripts/selfservice.js

small refactor in self-service.js

Small change

---

how-it-works/index.html
index.html
story/index.html
styles/main.css

"to" omitted in the sentence - now fixed.

text edit 

---

scripts/selfservice.js
self-service/index.html
styles/main.css

Left align headings and remove list bullets from rider info items

minor UI improvements

---

_includes/footer.html
_includes/nav.html
pages/faq.html
pages/how-it-works.html
pages/index.html
pages/self-service.html
pages/story.html
pages/terms-conditions.html
pages/thanks-driver.html
pages/thanks-rider.html

- Fix missing link URLs by adding trailing slashes to permalinks (Fixes #255)
- Make all internal links relative, to ensure that they work when the site is hosted on a subdirectory.
This PR is ready to merge.

Fix permalinks and urls

---

_includes/footer.html
_layouts/default.html
pages/index.html

Apparently liquid variable assignment doesn't work through nested includes (e.g. with layouts). So I'm importing this partial directly in files where it's used, to ensure that it works in index.html

Hotfix: Import API patch directly to files where it's used

---

pages/index.html

Replace volunteer offer form with link to volunteer survey
Fixes #261

Content update

---

pages/index.html

Addresses points 3,4,5 in issue #254

Site text changes

---

README.md

@sasjkia @richardwestenra This PR updates the main Readme for the frontend on github, which is presently out of date. Might help with attracting contributors 😄

updated Readme mention of activity from 2016 to 2017

---

scripts/selfservice.js

@richardwestenra this PR corrects various self-service behaviours to work as they did before (correctly). Changes outside this page had changed that. Other parts of this PR are minor improvements and changes (see commit list)
Fixes https://github.com/voteamerica/voteamerica.github.io/issues/283
Fixes https://github.com/voteamerica/backend/issues/146
Fixes https://github.com/voteamerica/backend/issues/130
Passed tests on docker setup

Self service page bug fixes and changes

---

_includes/nav.html
pages/faq.html

Fixes #285.
I found three locations. Hope I got them all.

Update to new number: 540-656-9388

---

pages/index.html

update rider signup passenger help text

---

_includes/footer.html
pages/index.html
scripts/home.js

Resolves part of #267 
If there is a better way to handle the callback / remove the global function and variables, please let me know!

Issue #267: implement google address autocomplete for driver signup 

---

pages/index.html

resolves subtask of #267 , per https://github.com/voteamerica/voteamerica.github.io/issues/267#issuecomment-302720227

add help text message at top of rider signup

---

_includes/nav.html

remove incorrect phone number in nav

---

pages/thanks-rider.html

Resolves #306 
- I did not create another paragraph to avoid having to change the javascript.
- to test, checkout this PR and navigate to `http://localhost:4000/thanks-rider/?code=0` (this was not obvious!)

add spam inbox reminder to successful signup page

---

pages/story.html

add link to state specific voter information to Our Story page

---

pages/story.html

change "Shrinking voter registration periods" to "Shrinking early voting periods"

---

pages/index.html
styles/main.css

Resolves #305 
- i did not think that the text wording was quite right, so i changed it - happy to revert the changes
- also updated the placeholder
- now `inline-block`, so the list appears to right of input on larger screens

update additional rider information text, position list to right of input

---

scripts/selfservice.js

Removes rider name, phone and email from driver proposed matches list
Fixes https://github.com/voteamerica/backend/issues/140
Fixes https://github.com/voteamerica/backend/issues/164

remove rider identifying info from driver proposed list

---

pages/index.html
styles/main.css

Fixes #314 
Fixes #315 
Fixes #316

Update Rider Sign Up

---

scripts/map.js
styles/main.css

resolves #324 
there might be a better way to handle this but this was the easiest way i could think of with my limited knowledge of the codebase.

notify user if participant map-related api calls error out

---

_includes/nav.html
styles/main.css

Replace 'voting info' link with 'My rides' in nav bar

---

scripts/map.js

also show wheelchair support. This is part of a change that can provide more information depending on feedback

Maps - add seat count display

---

_includes/nav.html

Add update for visitors to site

Visitor Update

---

docs/values.md
docs/working-together.md

Added both files to the docs folder. I did not add any links to the contributing.md.  Let me know if you want me and how you like me to change it. 
I pushed up the changes at first on the master branch.  Then I added the new branch and push up the changes that way.  They should be identical.

Added values.md and working-together.md file

---

_includes/nav.html

update twitter share button for 2018

---

_includes/nav.html

update twitter and facebook buttons to go to https version of carpoolvote site

---

_config.yml
_includes/nav.html
pages/thanks-driver.html
pages/thanks-rider.html

Relates to #406 
Updates main banner (more than requested in issue), also fixes thanks-driver/rider tweet dates

update main banner and some old dates

---

scripts/selfservice.js

driver proposed/confirmed - break up rider notes and contact methods, show dates, seats needed, and powerchair user and two way trip if relevant
rider confirmed match - show driver dates

Self service dates
